import Head from 'next/head'
import Script from 'next/script'
import NavBar from '../Components/NavBar'
import '../styles/globals.scss'

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Doctos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        
      </Head>
      <Script src="https://kit.fontawesome.com/937c5f2506.js" crossOrigin="anonymous" />
      <NavBar />
      <div className='container'>
        <Component {...pageProps} />
      </div>
    </>
  )
}
